version: "2"
services:
    alpine: alpine:3.6
    image: 
    cpu_share: 10  # 0.1core
    mem_limit: 100000000 # 10m
    environment:
      - ENV=demo
      - ENV_PROXY_HOST=proxy
      - ENV_PROXY_PORT=8118
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      aliyun.rolling_updates: 'true'
      aliyun.scale: '1'
      aliyun.log_store_alpine: stdout
    depends_on:
      - sslocal
    links:
      - sslocal:proxy
    restart: always
  sslocal:
    image: teachmyself/sslocal:latest
    environment:
      - reschedule:on-node-failure
      - SERVER_HOST=server_address
      - SERVER_PORT=8888
      - PASSWORD=Passw0rd
      - METHOD=aes-256-cfb
      - LOCAL_PORT=1080
      - PROXY_PORT=8118
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      aliyun.probe.url: tcp://container:8118
      aliyun.probe.initial_delay_seconds: 8
      aliyun.probe.timeout_seconds: 6
      aliyun.rolling_updates: 'true'
      aliyun.scale: '2'
      aliyun.log_store_sslocal: stdout
      aliyun.log_store_sslocal: /var/log/sslocal.log
    expose:
      - 8118
    restart: always
