version: '2'
services:
  jupyter:
    image: tensorflow    
    environment:
      - affinity:service!=jupyter
      - reschedule:on-node-failure
      - PASSWORD=tensorflow
    labels:
      aliyun.probe.url: tcp://container:8888
      aliyun.probe.timeout_seconds: 8
      aliyun.probe.initial_delay_seconds: 8
      aliyun.rolling_updates: 'true'
      aliyun.scale: '1'
      aliyun.log_store_jupyter: stdout
      aliyun.proxy.VIRTUAL_HOST: "tensorflow.live.teachmyself.cn"
      aliyun.proxy.required: 'true'
    expose:
      - '8888'
    volumes:
      - /etc/localtime:/etc/localtime
      - /tmp/tensorflow_logs
    restart: always
    command:
      - "/run_jupyter.sh"
  tensorboard:
    image: tensorflow    
    environment:
      - affinity:service!=tensorboard
      - reschedule:on-node-failure
      - PASSWORD=tensorflow
    labels:
      aliyun.probe.url: tcp://container:6006
      aliyun.probe.timeout_seconds: 8
      aliyun.probe.initial_delay_seconds: 8
      aliyun.rolling_updates: 'true'
      aliyun.scale: '1'
      aliyun.log_store_tensorboard: stdout
      aliyun.proxy.VIRTUAL_HOST: "tensorboard.live.teachmyself.cn"
      aliyun.proxy.required: 'true'
    volumes:
      - /etc/localtime:/etc/localtime:ro
    volumes_from:
      - jupyter
    expose:
      - '6006'
    restart: always
    command:
      - "tensorboard"
      - "--logdir"
      - "/tmp/tensorflow_logs"
      - "--host"
      - "0.0.0.0"
